spring.application.name=app-gateway
server.port=8089

jwt.secret=mi-super-secreto-de-al-menos-32-caracteres-para-hs256


# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

#RUTAS

# ms-core (8082)
spring.cloud.gateway.server.webmvc.routes[0].id=ms-core
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/core/**

# ms-auth (8083)
spring.cloud.gateway.server.webmvc.routes[1].id=ms-auth
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/auth/**

# ms-interno (8084)
spring.cloud.gateway.server.webmvc.routes[2].id=ms-interno
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/internos/**

# ms-judicial (8085)
spring.cloud.gateway.server.webmvc.routes[3].id=ms-judicial
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/v1/expedientes/**,/api/v1/documentos/**,/api/v1/mandatos/**,/api/v1/delitos/**

# ms-personal (8090)
spring.cloud.gateway.server.webmvc.routes[4].id=ms-personal
spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:8090
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/v1/personal/**

# ms-instituciones (8092)
spring.cloud.gateway.server.webmvc.routes[5].id=ms-instituciones
spring.cloud.gateway.server.webmvc.routes[5].uri=http://localhost:8092
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/v1/sedes/**,/api/v1/institutos/**

# ms-traslado (8093)
spring.cloud.gateway.server.webmvc.routes[6].id=ms-traslado
spring.cloud.gateway.server.webmvc.routes[6].uri=http://localhost:8093
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/v1/traslados/**,/traslados/**
# ms-persona (8094)
spring.cloud.gateway.server.webmvc.routes[7].id=ms-persona
spring.cloud.gateway.server.webmvc.routes[7].uri=http://localhost:8094
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/api/v1/persona/**